# Generated by Django 4.1.5 on 2023-01-19 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 0, 12, 136651, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
