# Generated by Django 4.1.5 on 2023-01-19 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 23, 1, 13, 637025, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
