# Generated by Django 4.1.5 on 2023-01-19 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 23, 2, 10, 622745, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
