# Generated by Django 4.1.5 on 2023-01-22 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_creator_alter_post_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
