# Generated by Django 4.1.5 on 2023-01-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
